### Panorama da família Flaviviridae

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)   # mostra todas as colunas
pd.set_option('display.width', None)         # não quebra linha por largura do terminal
pd.set_option('display.max_colwidth', 30)

from bio.ler_fasta import ler_fasta
from bio.sequencia import (
    traduzir,
    calcular_percentual_gc,
    encontrar_inicio,
)

### Parte 1 — Monte a tabela

In [4]:
organismos = ler_fasta("arquivos/Flaviviridae-genomes.fasta")
df = pd.DataFrame(organismos)
print(df.head())

            id                           nome                      sequencia
0  NC_074786.1  Guereza hepacivirus isolat...  CACTCCATACTACACTCCGCATTTGG...
1  NC_074787.1  Hepatitis GB virus A polyp...  CGTGGGAGTCCGGGGCCCCGGACCTC...
2  NC_076029.1  Bovine viral diarrhea viru...  GTATACGAGAACTAGATAAAATACTC...
3  NC_076032.1  Bovine viral diarrhea viru...  GTATACGAGATTAGCTAAAGTACTCG...
4  NC_077000.1  Rodent pestivirus isolate ...  TGTATAAGGAAGGGGTGGGAGCCTTC...

In [6]:
# Criando a coluna "tamanho"
df['tamanho'] = df.apply(lambda linha: len(linha['sequencia']), axis=1)

df.head()

,id,nome,sequencia,tamanho
0,NC_074786.1,Guereza hepacivirus isolat...,CACTCCATACTACACTCCGCATTTGG...,10412
1,NC_074787.1,Hepatitis GB virus A polyp...,CGTGGGAGTCCGGGGCCCCGGACCTC...,9653
2,NC_076029.1,Bovine viral diarrhea viru...,GTATACGAGAACTAGATAAAATACTC...,12308
3,NC_076032.1,Bovine viral diarrhea viru...,GTATACGAGATTAGCTAAAGTACTCG...,12284
4,NC_077000.1,Rodent pestivirus isolate ...,TGTATAAGGAAGGGGTGGGAGCCTTC...,12768

### Parte 2 — O conteúdo GC é aleatório?

In [8]:
# 1) crie a coluna "gc" com df["sequencia"].apply(calcular_percentual_gc)

df['gc'] = df['sequencia'].apply(calcular_percentual_gc)

df.head()

,id,nome,sequencia,tamanho,gc
0,NC_074786.1,Guereza hepacivirus isolat...,CACTCCATACTACACTCCGCATTTGG...,10412,0.53
1,NC_074787.1,Hepatitis GB virus A polyp...,CGTGGGAGTCCGGGGCCCCGGACCTC...,9653,0.57
2,NC_076029.1,Bovine viral diarrhea viru...,GTATACGAGAACTAGATAAAATACTC...,12308,0.46
3,NC_076032.1,Bovine viral diarrhea viru...,GTATACGAGATTAGCTAAAGTACTCG...,12284,0.45
4,NC_077000.1,Rodent pestivirus isolate ...,TGTATAAGGAAGGGGTGGGAGCCTTC...,12768,0.42

In [10]:
# 2) mostre os 10 maiores e os 10 menores GC (com o nome!) -> usar função sort_values do pandas

# 10 maiores conteúdos GC
print('\n10 maiores conteúdos GC')
df.sort_values(by='gc', ascending=False)[['nome', 'gc']].head(10)

10 maiores conteúdos GC

                              nome    gc
93   Norway rat pegivirus isola...  0.61
110  Rodent pegivirus isolate C...  0.61
28   Pegivirus F isolate PDB-16...  0.61
150  GB virus C/Hepatitis G vir...  0.59
31   Pegivirus I isolate PDB-17...  0.59
112  Equine Pegivirus 1 isolate...  0.58
147  Hepatitis C virus genotype...  0.58
146  Hepatitis GB virus A, comp...  0.58
32   Hepatitis C virus (isolate...  0.58
43   Pegivirus K isolate PPgV_9...  0.58

In [11]:
# 10 menores conteúdos GC
print('\n10 menores conteúdos GC')
df.sort_values(by='gc', ascending=True)[['nome', 'gc']].head(10)

10 menores conteúdos GC

                              nome    gc
5    Rodent pestivirus isolate ...  0.39
9    Phocoena pestivirus isolat...  0.39
8    Dongyang pangolin virus is...  0.40
92   Norway rat pestivirus isol...  0.41
4    Rodent pestivirus isolate ...  0.42
6    Bat pestivirus BtSk-PestV-...  0.43
104  Pronghorn antelope pestivi...  0.44
137  Montana myotis leukoenceph...  0.44
108  Porcine pestivirus isolate...  0.45
37   Bovine viral diarrhea viru...  0.45

In [ ]:
# 3) escreva sua conclusão sobre o padrão que observou

# Os pegivirus e hepatites apresentam os maiores conteúdos GC. Os pestivirus apresentam os menores conteúdos GC.

### Parte 3 — Encontre a proteína (a poliproteína viral)

In [12]:
# 1) coluna "proteina": traduzir(encontrar_inicio(seq), parar=True)

df['proteina'] = df['sequencia'].apply(lambda seq: traduzir(encontrar_inicio(seq), parar=True))

df

,id,nome,sequencia,tamanho,gc,proteina
0,NC_074786.1,Guereza hepacivirus isolat...,CACTCCATACTACACTCCGCATTTGG...,10412,0.53,MPGRRLLGWDGPQPGP
1,NC_074787.1,Hepatitis GB virus A polyp...,CGTGGGAGTCCGGGGCCCCGGACCTC...,9653,0.57,MPSVRVRRW
2,NC_076029.1,Bovine viral diarrhea viru...,GTATACGAGAACTAGATAAAATACTC...,12308,0.46,MNPSQRRPKGG
3,NC_076032.1,Bovine viral diarrhea viru...,GTATACGAGATTAGCTAAAGTACTCG...,12284,0.45,MDWTSTNF
4,NC_077000.1,Rodent pestivirus isolate ...,TGTATAAGGAAGGGGTGGGAGCCTTC...,12768,0.42,MQV
...,...,...,...,...,...,...
154,NC_001461.1,Bovine viral diarrhea viru...,GTATACGAGAATTAGAAAAGGCACTC...,12573,0.46,MPLVGLA
155,NC_001474.2,"Dengue virus 2, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10723,0.46,MNNQRKKAKNTPFNMLKRERNRVSTV...
156,NC_001475.2,"Dengue virus 3, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10707,0.47,MNNQRKKTGKPSINMLKRVRNRVSTG...
157,NC_003687.1,"Powassan virus, complete g...",AGATTTTCTTGCACGTGTGTGCGGGT...,10839,0.53,MMTTSKGKGGGPPRRKLKVTANKSRP...
158,NC_002031.1,"Yellow fever virus, comple...",AGTAAATCCTGTGTGCTAATTGAGGT...,10862,0.50,MSGRKAQGKTLGVNMVRRGVRSLSNK...

In [17]:
# 2) coluna "tamanho_proteina": len da proteína

df['tamanho_proteina'] = df['proteina'].apply(len)

df

,id,nome,sequencia,tamanho,gc,proteina,tamanho_proteina
0,NC_074786.1,Guereza hepacivirus isolat...,CACTCCATACTACACTCCGCATTTGG...,10412,0.53,MPGRRLLGWDGPQPGP,16
1,NC_074787.1,Hepatitis GB virus A polyp...,CGTGGGAGTCCGGGGCCCCGGACCTC...,9653,0.57,MPSVRVRRW,9
2,NC_076029.1,Bovine viral diarrhea viru...,GTATACGAGAACTAGATAAAATACTC...,12308,0.46,MNPSQRRPKGG,11
3,NC_076032.1,Bovine viral diarrhea viru...,GTATACGAGATTAGCTAAAGTACTCG...,12284,0.45,MDWTSTNF,8
4,NC_077000.1,Rodent pestivirus isolate ...,TGTATAAGGAAGGGGTGGGAGCCTTC...,12768,0.42,MQV,3
...,...,...,...,...,...,...,...
154,NC_001461.1,Bovine viral diarrhea viru...,GTATACGAGAATTAGAAAAGGCACTC...,12573,0.46,MPLVGLA,7
155,NC_001474.2,"Dengue virus 2, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10723,0.46,MNNQRKKAKNTPFNMLKRERNRVSTV...,3391
156,NC_001475.2,"Dengue virus 3, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10707,0.47,MNNQRKKTGKPSINMLKRVRNRVSTG...,3390
157,NC_003687.1,"Powassan virus, complete g...",AGATTTTCTTGCACGTGTGTGCGGGT...,10839,0.53,MMTTSKGKGGGPPRRKLKVTANKSRP...,3415
158,NC_002031.1,"Yellow fever virus, comple...",AGTAAATCCTGTGTGCTAATTGAGGT...,10862,0.50,MSGRKAQGKTLGVNMVRRGVRSLSNK...,3411

In [18]:
# 3) coluna "cobertura": (tamanho_proteina * 3) / tamanho

df['cobertura'] = df.apply(lambda linha: (linha['tamanho_proteina']*3) / linha['tamanho'], axis = 1)

df

,id,nome,sequencia,tamanho,gc,proteina,tamanho_proteina,cobertura
0,NC_074786.1,Guereza hepacivirus isolat...,CACTCCATACTACACTCCGCATTTGG...,10412,0.53,MPGRRLLGWDGPQPGP,16,0.004610
1,NC_074787.1,Hepatitis GB virus A polyp...,CGTGGGAGTCCGGGGCCCCGGACCTC...,9653,0.57,MPSVRVRRW,9,0.002797
2,NC_076029.1,Bovine viral diarrhea viru...,GTATACGAGAACTAGATAAAATACTC...,12308,0.46,MNPSQRRPKGG,11,0.002681
3,NC_076032.1,Bovine viral diarrhea viru...,GTATACGAGATTAGCTAAAGTACTCG...,12284,0.45,MDWTSTNF,8,0.001954
4,NC_077000.1,Rodent pestivirus isolate ...,TGTATAAGGAAGGGGTGGGAGCCTTC...,12768,0.42,MQV,3,0.000705
...,...,...,...,...,...,...,...,...
154,NC_001461.1,Bovine viral diarrhea viru...,GTATACGAGAATTAGAAAAGGCACTC...,12573,0.46,MPLVGLA,7,0.001670
155,NC_001474.2,"Dengue virus 2, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10723,0.46,MNNQRKKAKNTPFNMLKRERNRVSTV...,3391,0.948708
156,NC_001475.2,"Dengue virus 3, complete g...",AGTTGTTAGTCTACGTGGACCGACAA...,10707,0.47,MNNQRKKTGKPSINMLKRVRNRVSTG...,3390,0.949846
157,NC_003687.1,"Powassan virus, complete g...",AGATTTTCTTGCACGTGTGTGCGGGT...,10839,0.53,MMTTSKGKGGGPPRRKLKVTANKSRP...,3415,0.945198
158,NC_002031.1,"Yellow fever virus, comple...",AGTAAATCCTGTGTGCTAATTGAGGT...,10862,0.50,MSGRKAQGKTLGVNMVRRGVRSLSNK...,3411,0.942092

In [ ]:
# 4) escreva sua conclusão (qual a cobertura típica? faz sentido ser 1 poliproteína?)

## Parte 4 — Salve o resultado

In [19]:
# 1) filtre os vírus com gc > 0.5 (quantos são?)

filtro_gc = df['gc'] > 0.5

df_filtro_gc = df[filtro_gc]

In [ ]:
# 2) df.to_csv("resultado.csv", index=False)

df_filtro_gc.to_csv('resultado.csv', index=False)